[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"

[env]
DATABASE_URL = "libsql://database-claret-diamond-vercel-icfg-rswpbsot4jfgjq8attvxdhob.aws-us-east-1.turso.io"
TURSO_AUTH_TOKEN = "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NzgxMzM3MjksImlkIjoiMDE5ZTAxMDctODAwMS03NjE2LTgwYjgtYjU2ODZiNTBiNDI4IiwicmlkIjoiMDQzOTE3NmUtZmY1Ni00Y2FjLWFlNTQtYzVjY2U0NmM0MTk3In0.NB4YykvDF9vRwfbQZiFedg__Nbtgj-ItR9fd5lxZI0q4URNNwgKn8yvgMsIxbf94WlROlenQ0sIiIadvQMTZDg"
